// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: peptides.proto
// Protobuf Java Version: 4.29.3

package hr.pbf.digested.proto;

public final class Peptides {
  private Peptides() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Peptides.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SeqAccessionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.pbf.digested.proto.SeqAccessions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * e.g. 20 different amino-acid letters
     * </pre>
     *
     * <code>string seq = 1;</code>
     * @return The seq.
     */
    java.lang.String getSeq();
    /**
     * <pre>
     * e.g. 20 different amino-acid letters
     * </pre>
     *
     * <code>string seq = 1;</code>
     * @return The bytes for seq.
     */
    com.google.protobuf.ByteString
        getSeqBytes();

    /**
     * <pre>
     * Handles values up to 252,064,061 (varint)
     * </pre>
     *
     * <code>repeated uint32 accessions = 2;</code>
     * @return A list containing the accessions.
     */
    java.util.List<java.lang.Integer> getAccessionsList();
    /**
     * <pre>
     * Handles values up to 252,064,061 (varint)
     * </pre>
     *
     * <code>repeated uint32 accessions = 2;</code>
     * @return The count of accessions.
     */
    int getAccessionsCount();
    /**
     * <pre>
     * Handles values up to 252,064,061 (varint)
     * </pre>
     *
     * <code>repeated uint32 accessions = 2;</code>
     * @param index The index of the element to return.
     * @return The accessions at the given index.
     */
    int getAccessions(int index);
  }
  /**
   * Protobuf type {@code hr.pbf.digested.proto.SeqAccessions}
   */
  public static final class SeqAccessions extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.pbf.digested.proto.SeqAccessions)
      SeqAccessionsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SeqAccessions.class.getName());
    }
    // Use SeqAccessions.newBuilder() to construct.
    private SeqAccessions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SeqAccessions() {
      seq_ = "";
      accessions_ = emptyIntList();
    }

    public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessions_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.pbf.digested.proto.Peptides.SeqAccessions.class, hr.pbf.digested.proto.Peptides.SeqAccessions.Builder.class);
    }

    public static final int SEQ_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object seq_ = "";
    /**
     * <pre>
     * e.g. 20 different amino-acid letters
     * </pre>
     *
     * <code>string seq = 1;</code>
     * @return The seq.
     */
    @java.lang.Override
    public java.lang.String getSeq() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seq_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * e.g. 20 different amino-acid letters
     * </pre>
     *
     * <code>string seq = 1;</code>
     * @return The bytes for seq.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSeqBytes() {
      java.lang.Object ref = seq_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESSIONS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList accessions_ =
        emptyIntList();
    /**
     * <pre>
     * Handles values up to 252,064,061 (varint)
     * </pre>
     *
     * <code>repeated uint32 accessions = 2;</code>
     * @return A list containing the accessions.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getAccessionsList() {
      return accessions_;
    }
    /**
     * <pre>
     * Handles values up to 252,064,061 (varint)
     * </pre>
     *
     * <code>repeated uint32 accessions = 2;</code>
     * @return The count of accessions.
     */
    public int getAccessionsCount() {
      return accessions_.size();
    }
    /**
     * <pre>
     * Handles values up to 252,064,061 (varint)
     * </pre>
     *
     * <code>repeated uint32 accessions = 2;</code>
     * @param index The index of the element to return.
     * @return The accessions at the given index.
     */
    public int getAccessions(int index) {
      return accessions_.getInt(index);
    }
    private int accessionsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(seq_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, seq_);
      }
      if (getAccessionsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(accessionsMemoizedSerializedSize);
      }
      for (int i = 0; i < accessions_.size(); i++) {
        output.writeUInt32NoTag(accessions_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(seq_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, seq_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < accessions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(accessions_.getInt(i));
        }
        size += dataSize;
        if (!getAccessionsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        accessionsMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SeqAccessions other)) {
        return super.equals(obj);
      }

        if (!getSeq()
          .equals(other.getSeq())) return false;
      if (!getAccessionsList()
          .equals(other.getAccessionsList())) return false;
        return getUnknownFields().equals(other.getUnknownFields());
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq().hashCode();
      if (getAccessionsCount() > 0) {
        hash = (37 * hash) + ACCESSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getAccessionsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.pbf.digested.proto.Peptides.SeqAccessions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.pbf.digested.proto.SeqAccessions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.pbf.digested.proto.SeqAccessions)
        hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder {
      public static com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessions_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.pbf.digested.proto.Peptides.SeqAccessions.class, hr.pbf.digested.proto.Peptides.SeqAccessions.Builder.class);
      }

      // Construct using hr.pbf.digested.proto.Peptides.SeqAccessions.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        seq_ = "";
        accessions_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessions_descriptor;
      }

      @java.lang.Override
      public hr.pbf.digested.proto.Peptides.SeqAccessions getDefaultInstanceForType() {
        return hr.pbf.digested.proto.Peptides.SeqAccessions.getDefaultInstance();
      }

      @java.lang.Override
      public hr.pbf.digested.proto.Peptides.SeqAccessions build() {
        hr.pbf.digested.proto.Peptides.SeqAccessions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public hr.pbf.digested.proto.Peptides.SeqAccessions buildPartial() {
        hr.pbf.digested.proto.Peptides.SeqAccessions result = new hr.pbf.digested.proto.Peptides.SeqAccessions(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(hr.pbf.digested.proto.Peptides.SeqAccessions result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.seq_ = seq_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          accessions_.makeImmutable();
          result.accessions_ = accessions_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.pbf.digested.proto.Peptides.SeqAccessions) {
          return mergeFrom((hr.pbf.digested.proto.Peptides.SeqAccessions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.pbf.digested.proto.Peptides.SeqAccessions other) {
        if (other == hr.pbf.digested.proto.Peptides.SeqAccessions.getDefaultInstance()) return this;
        if (!other.getSeq().isEmpty()) {
          seq_ = other.seq_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.accessions_.isEmpty()) {
          if (accessions_.isEmpty()) {
            accessions_ = other.accessions_;
            accessions_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureAccessionsIsMutable();
            accessions_.addAll(other.accessions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                seq_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                int v = input.readUInt32();
                ensureAccessionsIsMutable();
                accessions_.addInt(v);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureAccessionsIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  accessions_.addInt(input.readUInt32());
                }
                input.popLimit(limit);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object seq_ = "";
      /**
       * <pre>
       * e.g. 20 different amino-acid letters
       * </pre>
       *
       * <code>string seq = 1;</code>
       * @return The seq.
       */
      public java.lang.String getSeq() {
        java.lang.Object ref = seq_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          seq_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * e.g. 20 different amino-acid letters
       * </pre>
       *
       * <code>string seq = 1;</code>
       * @return The bytes for seq.
       */
      public com.google.protobuf.ByteString
          getSeqBytes() {
        java.lang.Object ref = seq_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          seq_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * e.g. 20 different amino-acid letters
       * </pre>
       *
       * <code>string seq = 1;</code>
       * @param value The seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeq(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        seq_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g. 20 different amino-acid letters
       * </pre>
       *
       * <code>string seq = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeq() {
        seq_ = getDefaultInstance().getSeq();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * e.g. 20 different amino-acid letters
       * </pre>
       *
       * <code>string seq = 1;</code>
       * @param value The bytes for seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeqBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        seq_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList accessions_ = emptyIntList();
      private void ensureAccessionsIsMutable() {
        if (!accessions_.isModifiable()) {
          accessions_ = makeMutableCopy(accessions_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <pre>
       * Handles values up to 252,064,061 (varint)
       * </pre>
       *
       * <code>repeated uint32 accessions = 2;</code>
       * @return A list containing the accessions.
       */
      public java.util.List<java.lang.Integer>
          getAccessionsList() {
        accessions_.makeImmutable();
        return accessions_;
      }
      /**
       * <pre>
       * Handles values up to 252,064,061 (varint)
       * </pre>
       *
       * <code>repeated uint32 accessions = 2;</code>
       * @return The count of accessions.
       */
      public int getAccessionsCount() {
        return accessions_.size();
      }
      /**
       * <pre>
       * Handles values up to 252,064,061 (varint)
       * </pre>
       *
       * <code>repeated uint32 accessions = 2;</code>
       * @param index The index of the element to return.
       * @return The accessions at the given index.
       */
      public int getAccessions(int index) {
        return accessions_.getInt(index);
      }
      /**
       * <pre>
       * Handles values up to 252,064,061 (varint)
       * </pre>
       *
       * <code>repeated uint32 accessions = 2;</code>
       * @param index The index to set the value at.
       * @param value The accessions to set.
       * @return This builder for chaining.
       */
      public Builder setAccessions(
          int index, int value) {

        ensureAccessionsIsMutable();
        accessions_.setInt(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Handles values up to 252,064,061 (varint)
       * </pre>
       *
       * <code>repeated uint32 accessions = 2;</code>
       * @param value The accessions to add.
       * @return This builder for chaining.
       */
      public Builder addAccessions(int value) {

        ensureAccessionsIsMutable();
        accessions_.addInt(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Handles values up to 252,064,061 (varint)
       * </pre>
       *
       * <code>repeated uint32 accessions = 2;</code>
       * @param values The accessions to add.
       * @return This builder for chaining.
       */
      public Builder addAllAccessions(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAccessionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, accessions_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Handles values up to 252,064,061 (varint)
       * </pre>
       *
       * <code>repeated uint32 accessions = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessions() {
        accessions_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hr.pbf.digested.proto.SeqAccessions)
    }

    // @@protoc_insertion_point(class_scope:hr.pbf.digested.proto.SeqAccessions)
    private static final hr.pbf.digested.proto.Peptides.SeqAccessions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.pbf.digested.proto.Peptides.SeqAccessions();
    }

    public static hr.pbf.digested.proto.Peptides.SeqAccessions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SeqAccessions>
        PARSER = new com.google.protobuf.AbstractParser<SeqAccessions>() {
      @java.lang.Override
      public SeqAccessions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SeqAccessions> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SeqAccessions> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public hr.pbf.digested.proto.Peptides.SeqAccessions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SeqAccessionListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.pbf.digested.proto.SeqAccessionList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    java.util.List<hr.pbf.digested.proto.Peptides.SeqAccessions>
        getSequencesList();
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    hr.pbf.digested.proto.Peptides.SeqAccessions getSequences(int index);
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    int getSequencesCount();
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    java.util.List<? extends hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder>
        getSequencesOrBuilderList();
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder getSequencesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code hr.pbf.digested.proto.SeqAccessionList}
   */
  public static final class SeqAccessionList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.pbf.digested.proto.SeqAccessionList)
      SeqAccessionListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        SeqAccessionList.class.getName());
    }
    // Use SeqAccessionList.newBuilder() to construct.
    private SeqAccessionList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SeqAccessionList() {
      sequences_ = java.util.Collections.emptyList();
    }

    public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessionList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.pbf.digested.proto.Peptides.SeqAccessionList.class, hr.pbf.digested.proto.Peptides.SeqAccessionList.Builder.class);
    }

    public static final int SEQUENCES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<hr.pbf.digested.proto.Peptides.SeqAccessions> sequences_;
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    @java.lang.Override
    public java.util.List<hr.pbf.digested.proto.Peptides.SeqAccessions> getSequencesList() {
      return sequences_;
    }
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder>
        getSequencesOrBuilderList() {
      return sequences_;
    }
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    @java.lang.Override
    public int getSequencesCount() {
      return sequences_.size();
    }
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    @java.lang.Override
    public hr.pbf.digested.proto.Peptides.SeqAccessions getSequences(int index) {
      return sequences_.get(index);
    }
    /**
     * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
     */
    @java.lang.Override
    public hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder getSequencesOrBuilder(
        int index) {
      return sequences_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < sequences_.size(); i++) {
        output.writeMessage(1, sequences_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sequences_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sequences_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SeqAccessionList other)) {
        return super.equals(obj);
      }

        if (!getSequencesList()
          .equals(other.getSequencesList())) return false;
        return getUnknownFields().equals(other.getUnknownFields());
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSequencesCount() > 0) {
        hash = (37 * hash) + SEQUENCES_FIELD_NUMBER;
        hash = (53 * hash) + getSequencesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static hr.pbf.digested.proto.Peptides.SeqAccessionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.pbf.digested.proto.Peptides.SeqAccessionList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.pbf.digested.proto.SeqAccessionList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.pbf.digested.proto.SeqAccessionList)
        hr.pbf.digested.proto.Peptides.SeqAccessionListOrBuilder {
      public static com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessionList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessionList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.pbf.digested.proto.Peptides.SeqAccessionList.class, hr.pbf.digested.proto.Peptides.SeqAccessionList.Builder.class);
      }

      // Construct using hr.pbf.digested.proto.Peptides.SeqAccessionList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (sequencesBuilder_ == null) {
          sequences_ = java.util.Collections.emptyList();
        } else {
          sequences_ = null;
          sequencesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.pbf.digested.proto.Peptides.internal_static_hr_pbf_digested_proto_SeqAccessionList_descriptor;
      }

      @java.lang.Override
      public hr.pbf.digested.proto.Peptides.SeqAccessionList getDefaultInstanceForType() {
        return hr.pbf.digested.proto.Peptides.SeqAccessionList.getDefaultInstance();
      }

      @java.lang.Override
      public hr.pbf.digested.proto.Peptides.SeqAccessionList build() {
        hr.pbf.digested.proto.Peptides.SeqAccessionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public hr.pbf.digested.proto.Peptides.SeqAccessionList buildPartial() {
        hr.pbf.digested.proto.Peptides.SeqAccessionList result = new hr.pbf.digested.proto.Peptides.SeqAccessionList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(hr.pbf.digested.proto.Peptides.SeqAccessionList result) {
        if (sequencesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            sequences_ = java.util.Collections.unmodifiableList(sequences_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sequences_ = sequences_;
        } else {
          result.sequences_ = sequencesBuilder_.build();
        }
      }

      private void buildPartial0(hr.pbf.digested.proto.Peptides.SeqAccessionList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.pbf.digested.proto.Peptides.SeqAccessionList) {
          return mergeFrom((hr.pbf.digested.proto.Peptides.SeqAccessionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.pbf.digested.proto.Peptides.SeqAccessionList other) {
        if (other == hr.pbf.digested.proto.Peptides.SeqAccessionList.getDefaultInstance()) return this;
        if (sequencesBuilder_ == null) {
          if (!other.sequences_.isEmpty()) {
            if (sequences_.isEmpty()) {
              sequences_ = other.sequences_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSequencesIsMutable();
              sequences_.addAll(other.sequences_);
            }
            onChanged();
          }
        } else {
          if (!other.sequences_.isEmpty()) {
            if (sequencesBuilder_.isEmpty()) {
              sequencesBuilder_.dispose();
              sequencesBuilder_ = null;
              sequences_ = other.sequences_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sequencesBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSequencesFieldBuilder() : null;
            } else {
              sequencesBuilder_.addAllMessages(other.sequences_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                hr.pbf.digested.proto.Peptides.SeqAccessions m =
                    input.readMessage(
                        hr.pbf.digested.proto.Peptides.SeqAccessions.parser(),
                        extensionRegistry);
                if (sequencesBuilder_ == null) {
                  ensureSequencesIsMutable();
                  sequences_.add(m);
                } else {
                  sequencesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<hr.pbf.digested.proto.Peptides.SeqAccessions> sequences_ =
        java.util.Collections.emptyList();
      private void ensureSequencesIsMutable() {
        if ((bitField0_ & 0x00000001) == 0) {
          sequences_ = new java.util.ArrayList<hr.pbf.digested.proto.Peptides.SeqAccessions>(sequences_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          hr.pbf.digested.proto.Peptides.SeqAccessions, hr.pbf.digested.proto.Peptides.SeqAccessions.Builder, hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder> sequencesBuilder_;

      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public java.util.List<hr.pbf.digested.proto.Peptides.SeqAccessions> getSequencesList() {
        if (sequencesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sequences_);
        } else {
          return sequencesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public int getSequencesCount() {
        if (sequencesBuilder_ == null) {
          return sequences_.size();
        } else {
          return sequencesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public hr.pbf.digested.proto.Peptides.SeqAccessions getSequences(int index) {
        if (sequencesBuilder_ == null) {
          return sequences_.get(index);
        } else {
          return sequencesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder setSequences(
          int index, hr.pbf.digested.proto.Peptides.SeqAccessions value) {
        if (sequencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSequencesIsMutable();
          sequences_.set(index, value);
          onChanged();
        } else {
          sequencesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder setSequences(
          int index, hr.pbf.digested.proto.Peptides.SeqAccessions.Builder builderForValue) {
        if (sequencesBuilder_ == null) {
          ensureSequencesIsMutable();
          sequences_.set(index, builderForValue.build());
          onChanged();
        } else {
          sequencesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder addSequences(hr.pbf.digested.proto.Peptides.SeqAccessions value) {
        if (sequencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSequencesIsMutable();
          sequences_.add(value);
          onChanged();
        } else {
          sequencesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder addSequences(
          int index, hr.pbf.digested.proto.Peptides.SeqAccessions value) {
        if (sequencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSequencesIsMutable();
          sequences_.add(index, value);
          onChanged();
        } else {
          sequencesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder addSequences(
          hr.pbf.digested.proto.Peptides.SeqAccessions.Builder builderForValue) {
        if (sequencesBuilder_ == null) {
          ensureSequencesIsMutable();
          sequences_.add(builderForValue.build());
          onChanged();
        } else {
          sequencesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder addSequences(
          int index, hr.pbf.digested.proto.Peptides.SeqAccessions.Builder builderForValue) {
        if (sequencesBuilder_ == null) {
          ensureSequencesIsMutable();
          sequences_.add(index, builderForValue.build());
          onChanged();
        } else {
          sequencesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder addAllSequences(
          java.lang.Iterable<? extends hr.pbf.digested.proto.Peptides.SeqAccessions> values) {
        if (sequencesBuilder_ == null) {
          ensureSequencesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sequences_);
          onChanged();
        } else {
          sequencesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder clearSequences() {
        if (sequencesBuilder_ == null) {
          sequences_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sequencesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public Builder removeSequences(int index) {
        if (sequencesBuilder_ == null) {
          ensureSequencesIsMutable();
          sequences_.remove(index);
          onChanged();
        } else {
          sequencesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public hr.pbf.digested.proto.Peptides.SeqAccessions.Builder getSequencesBuilder(
          int index) {
        return getSequencesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder getSequencesOrBuilder(
          int index) {
        if (sequencesBuilder_ == null) {
          return sequences_.get(index);  } else {
          return sequencesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public java.util.List<? extends hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder>
           getSequencesOrBuilderList() {
        if (sequencesBuilder_ != null) {
          return sequencesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sequences_);
        }
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public hr.pbf.digested.proto.Peptides.SeqAccessions.Builder addSequencesBuilder() {
        return getSequencesFieldBuilder().addBuilder(
            hr.pbf.digested.proto.Peptides.SeqAccessions.getDefaultInstance());
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public hr.pbf.digested.proto.Peptides.SeqAccessions.Builder addSequencesBuilder(
          int index) {
        return getSequencesFieldBuilder().addBuilder(
            index, hr.pbf.digested.proto.Peptides.SeqAccessions.getDefaultInstance());
      }
      /**
       * <code>repeated .hr.pbf.digested.proto.SeqAccessions sequences = 1;</code>
       */
      public java.util.List<hr.pbf.digested.proto.Peptides.SeqAccessions.Builder>
           getSequencesBuilderList() {
        return getSequencesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          hr.pbf.digested.proto.Peptides.SeqAccessions, hr.pbf.digested.proto.Peptides.SeqAccessions.Builder, hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder>
          getSequencesFieldBuilder() {
        if (sequencesBuilder_ == null) {
          sequencesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              hr.pbf.digested.proto.Peptides.SeqAccessions, hr.pbf.digested.proto.Peptides.SeqAccessions.Builder, hr.pbf.digested.proto.Peptides.SeqAccessionsOrBuilder>(
                  sequences_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          sequences_ = null;
        }
        return sequencesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:hr.pbf.digested.proto.SeqAccessionList)
    }

    // @@protoc_insertion_point(class_scope:hr.pbf.digested.proto.SeqAccessionList)
    private static final hr.pbf.digested.proto.Peptides.SeqAccessionList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.pbf.digested.proto.Peptides.SeqAccessionList();
    }

    public static hr.pbf.digested.proto.Peptides.SeqAccessionList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SeqAccessionList>
        PARSER = new com.google.protobuf.AbstractParser<SeqAccessionList>() {
      @java.lang.Override
      public SeqAccessionList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SeqAccessionList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SeqAccessionList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public hr.pbf.digested.proto.Peptides.SeqAccessionList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_pbf_digested_proto_SeqAccessions_descriptor;
  private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_pbf_digested_proto_SeqAccessions_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_pbf_digested_proto_SeqAccessionList_descriptor;
  private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_pbf_digested_proto_SeqAccessionList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016peptides.proto\022\025hr.pbf.digested.proto\"" +
      "0\n\rSeqAccessions\022\013\n\003seq\030\001 \001(\t\022\022\n\naccessi" +
      "ons\030\002 \003(\r\"K\n\020SeqAccessionList\0227\n\tsequenc" +
      "es\030\001 \003(\0132$.hr.pbf.digested.proto.SeqAcce" +
      "ssionsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hr_pbf_digested_proto_SeqAccessions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hr_pbf_digested_proto_SeqAccessions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_pbf_digested_proto_SeqAccessions_descriptor,
        new java.lang.String[] { "Seq", "Accessions", });
    internal_static_hr_pbf_digested_proto_SeqAccessionList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hr_pbf_digested_proto_SeqAccessionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_pbf_digested_proto_SeqAccessionList_descriptor,
        new java.lang.String[] { "Sequences", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
